#!/bin/bash
# wingcool bind action
# ... see: /etc/udev/rules.d/95-drm-change.rules

sudo --user=bryan \
  /home/bryan/.nix-profile/bin/xinput-wingcool-bind \
  &>> /tmp/wingcool-bind.log

# vim: ft=bash:
